# PR to dev/main, run tests and create review
name: Pull Request CI

on:
  pull_request:
    #    branches-ignore:
    #      - 'main'
    paths:
      - 'src/**'

jobs:
  ci-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        node: [ 14 ]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install
        run: yarn install --frozen-lockfile

      - name: Test
        run: yarn test
